# spring.application.name=clanes-crud
# #DataBase Settings

# spring.datasource.url=jdbc:mysql://localhost:3307/riwi_clanCrud_DB
# spring.datasource.username=user
# spring.datasource.password=password
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# # Server Settings
# server.port=8080
# server.servlet.context-path=/api

# #JPA Settings
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.datasource.hikari.connection-timeout=80000

# #Dialect
# spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring:
  application:
    name: clanes-crud

  datasource:
    url: jdbc:mysql://localhost:3307/riwi_clanCrud_DB
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 80000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 0
  servlet:
    context-path: /api/v1

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
